blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/Matthias-GOUDJIL/aion/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
